export default {
    js: "JavaScript",
    python: "Python",
    sqlite: "MySQL",
    php: "PHP",
    c: "C++",
    wordpress: "WordPress",
    wordpressDev: "WP 𝗗𝗲𝘃𝗲𝗹𝗼𝗽𝗺𝗲𝗻𝘁",
    wordpressCo: "WP 𝗖𝘂𝘀𝘁𝗼𝗺𝗶𝘇𝗮𝘁𝗶𝗼𝗻",
    wordpressTD: "WP 𝗧𝗵𝗲𝗺𝗲 𝗗𝗲𝘃𝗲𝗹𝗼𝗽𝗺𝗲𝗻𝘁",
    wordpressM: "WP 𝗠𝗮𝗶𝗻𝘁𝗲𝗻𝗮𝗻𝗰𝗲",
    wordpressS: "WP 𝗦𝗲𝗰𝘂𝗿𝗶𝘁𝘆",
    wprdpressSo: "WP 𝗦𝗽𝗲𝗲𝗱 𝗢𝗽𝘁𝗶𝗺𝗶𝘇𝗮𝘁𝗶𝗼𝗻",
    postgreSql: "PostgreSQL",
    figmatowp: "Figma to WordPress",
    html: "HTML",
    css: "CSS",
    sass: "SASS",
    scss: "SCSS",
    node: "Node.js",
    vscode: "VSCode",
    figma: "Figma",
    git: "Git & GitHub",
    webpack: "WebPack",
    canva: "Canva",
    pug: "Pug",
    gulp: "Gulp",
    next: "Next",
    deno: "Deno",
    pixijs: "PixiJS",
    preact: "Preact",
    elementor: "Elementor",
    divi: "Divi",
    woocommerce: "Woocommerce",
    jetPlugins: "Jet Plugins",
    sliderRevolution: "Slider Revolution",
    googleAnalytics: "Google Analytics",
    contactForm: "Contact Form 7",
    crocoBlock: "Crocoblock ",
    ultimateM: "Ultimate Member",
    revslider: "Revslider",
    smartcrop: "WordPress Smartcrop",
    scroll: "Mousewheel Smooth Scroll",
    shopify: "Shopify",
}